### ISSUE TITLE
Midi Device issue

### ISSUE THREAD

**Issue by l8on** [heronarts/LX#15]
I have a Korg NanoKontrol2 that definitely worked with the dome when it was running P2LX.
I get the following error when it is simply plugged in as the `LXMidiEngine` tries to get the device info for the plugged in device. 
```
java.lang.IllegalArgumentException: Requested device not installed: SLIDER/KNOB
	at javax.sound.midi.MidiSystem.getMidiDevice(MidiSystem.java:226)
	at uk.co.xfactorylibrarians.coremidi4j.CoreMidiDeviceProvider.getMidiDeviceInfo(CoreMidiDeviceProvider.java:422)
	at heronarts.lx.midi.LXMidiEngine$1.run(Unknown Source)
```

I think I may just get a new device, but if you have any ideas for how to "install" my device such that it doesn't crash, I'm all ears.

**Comment by mcslee** [comment]
Wow that is bizarre, never seen that one. I'm sure you googled it as well. I found very few references to this error. I'll fix up the code so that at least it doesn't crash out, will handle that exception and ignore the device instead.

I think there is a dedicated driver for the Korg nano thing? Try reinstalling it? I've used that one with LX before plenty of times without issue, so not sure what's up with this.

**Comment by mcslee** [comment]
This is the best I can offer:
https://github.com/heronarts/LX/commit/844be47c011f6d8afde9b7b75802e71f3bad2ad4

I think this uncaught raw Exception is happening in here:
https://github.com/DerekCook/CoreMidi4J/blob/master/CoreMIDI4J/src/uk/co/xfactorylibrarians/coremidi4j/CoreMidiDeviceProvider.java#L429

That's a real weird one. Sorry this is the best I can do right now.

**Comment by l8on** [comment]
Hey @mcslee thanks for making those changes, I was able to get it working with a very similar code change, but I didn't have Internet at the time.

Basically, some library is throwing the wrong exception. It should be throwing the `MidiUnavailableException` but for some reason it is throwing an `IllegalArgumentException`. Catching that error fixed the crash, and the midi controller does indeed still work!
