### ISSUE TITLE
Support for MIDI beat clock signals

### ISSUE THREAD

**Issue by awhitty** [heronarts/LX#4]
Howdy!

I love this library and have been using it for a smallish array of lights in conjunction largely with DJ sets. 

I would love to use the MIDI clock signal that Traktor/Live/etc. output to sync the tempo control to the master machine playing music. It looks like the `TIMING_CLOCK`, `START`, and `STOP` messages are discarded by the `LXMidiEngine`'s `dispatch` function. I've had luck with the MIDI clock signals on my own primitive approach to a LED engine, and I think they would be super useful here.

I intend to submit some PRs to incorporate the signals in a pluggable way, but I'm definitely still learning/exploring LX, and I want to discuss how to organize things to follow the work you've been doing.

In the meantime, thanks so much for this resource!

**Comment by mcslee** [comment]
Hey Austin - sounds like a reasonable thing to enable for sure. Note that there is a global "tempo" object in LX, which does have a tap() method. Shouldn't be too tough to add something similar which would route MIDI clock signals using a similar methodology. I believe MIDI clock is 24 ticks per quarter note, so the simplest implementation might just count 24 ticks and call tap().

Note that tap() has its own internal counting/averaging logic:
https://github.com/heronarts/LX/blob/master/src/heronarts/lx/Tempo.java#L191

You probably don't really need this with MIDI clock, since it's already doing a reasonably high-resolution counting.

In any event, that's my advice:
(1) Add a boolean method, something like enableMidiClock() on LXMidiInput
(2) If enabled, stop discarding those messages, have them call to the Tempo object

**Comment by awhitty** [comment]
Howdy, #5 accomplishes pretty much what I've intended. Please give it a look over and let me know if you'd like me to tighten anything up. I had to add an unsmoothed variant of the `tap()` logic, and that opened up an idea that takes this a bit overkill: to have a `tap(24)` method that can handle the individual 1/24th note ticks and extrapolate the bpm from there.

**Comment by mcslee** [comment]
Cool - generally looks good to me, I left a few minor comments. Clean those
up and I'll merge this in, thanks! I don't think you need a separate
tap(24) method. The way you're using the midiClockCounter() is already
effectively doing that smoothing... it'll naturally average the 24 clicks
out to one quarter note.

**Comment by awhitty** [comment]
Awesome, thanks for the feedback! I'll incorporate it in a bit.

My thought behind the `tap(24)` method is that if a midi clock changes tempo quickly, the internal Tempo object will take about a beat to update to the new tempo. A higher-resolution `tap` method would make this a more seamless transition.
